export const countriesMap={
	"ad": "Andorra",
	"ae": "United Arab Emirates",
	"af": "Afghanistan",
	"ag": "Antigua and Barbuda",
	"ai": "Anguilla",
	"al": "Albania",
	"am": "Armenia",
	"ao": "Angola",
	"aq": "Antarctica",
	"ar": "Argentina",
	"as": "American Samoa",
	"at": "Austria",
	"au": "Australia",
	"aw": "Aruba",
	"ax": "Åland Islands",
	"az": "Azerbaijan",
	"ba": "Bosnia and Herzegovina",
	"bb": "Barbados",
	"bd": "Bangladesh",
	"be": "Belgium",
	"bf": "Burkina Faso",
	"bg": "Bulgaria",
	"bh": "Bahrain",
	"bi": "Burundi",
	"bj": "Benin",
	"bl": "Saint Barthélemy",
	"bm": "Bermuda",
	"bn": "Brunei",
	"bo": "Bolivia",
	"bq": "Caribbean Netherlands",
	"br": "Brazil",
	"bs": "Bahamas",
	"bt": "Bhutan",
	"bv": "Bouvet Island",
	"bw": "Botswana",
	"by": "Belarus",
	"bz": "Belize",
	"ca": "Canada",
	"cc": "Cocos (Keeling) Islands",
	"cd": "DR Congo",
	"cf": "Central African Republic",
	"cg": "Republic of the Congo",
	"ch": "Switzerland",
	"ci": "Côte d'Ivoire (Ivory Coast)",
	"ck": "Cook Islands",
	"cl": "Chile",
	"cm": "Cameroon",
	"cn": "China",
	"co": "Colombia",
	"cr": "Costa Rica",
	"cu": "Cuba",
	"cv": "Cape Verde",
	"cw": "Curaçao",
	"cx": "Christmas Island",
	"cy": "Cyprus",
	"cz": "Czechia",
	"de": "Germany",
	"dj": "Djibouti",
	"dk": "Denmark",
	"dm": "Dominica",
	"do": "Dominican Republic",
	"dz": "Algeria",
	"ec": "Ecuador",
	"ee": "Estonia",
	"eg": "Egypt",
	"eh": "Western Sahara",
	"er": "Eritrea",
	"es": "Spain",
	"et": "Ethiopia",
	"eu": "European Union",
	"fi": "Finland",
	"fj": "Fiji",
	"fk": "Falkland Islands",
	"fm": "Micronesia",
	"fo": "Faroe Islands",
	"fr": "France",
	"ga": "Gabon",
	"gb": "United Kingdom",
	"gb-ng": "England",
	"gb-ir": "Northern Ireland",
	"gb-ct": "Scotland",
	"gb-ls": "Wales",
	"gd": "Grenada",
	"ge": "Georgia",
	"gf": "French Guiana",
	"gg": "Guernsey",
	"gh": "Ghana",
	"gi": "Gibraltar",
	"gl": "Greenland",
	"gm": "Gambia",
	"gn": "Guinea",
	"gp": "Guadeloupe",
	"gq": "Equatorial Guinea",
	"gr": "Greece",
	"gs": "South Georgia",
	"gt": "Guatemala",
	"gu": "Guam",
	"gw": "Guinea-Bissau",
	"gy": "Guyana",
	"hk": "Hong Kong",
	"hm": "Heard Island and McDonald Islands",
	"hn": "Honduras",
	"hr": "Croatia",
	"ht": "Haiti",
	"hu": "Hungary",
	"id": "Indonesia",
	"ie": "Ireland",
	"il": "Israel",
	"im": "Isle of Man",
	"in": "India",
	"io": "British Indian Ocean Territory",
	"iq": "Iraq",
	"ir": "Iran",
	"is": "Iceland",
	"it": "Italy",
	"je": "Jersey",
	"jm": "Jamaica",
	"jo": "Jordan",
	"jp": "Japan",
	"ke": "Kenya",
	"kg": "Kyrgyzstan",
	"kh": "Cambodia",
	"ki": "Kiribati",
	"km": "Comoros",
	"kn": "Saint Kitts and Nevis",
	"kp": "North Korea",
	"-": "Korea",
	"kr": "South Korea",
	"kw": "Kuwait",
	"ky": "Cayman Islands",
	"kz": "Kazakhstan",
	"la": "Laos",
	"lb": "Lebanon",
	"lc": "Saint Lucia",
	"li": "Liechtenstein",
	"lk": "Sri Lanka",
	"lr": "Liberia",
	"ls": "Lesotho",
	"lt": "Lithuania",
	"lu": "Luxembourg",
	"lv": "Latvia",
	"ly": "Libya",
	"ma": "Morocco",
	"mc": "Monaco",
	"md": "Moldova",
	"me": "Montenegro",
	"mf": "Saint Martin",
	"mg": "Madagascar",
	"mh": "Marshall Islands",
	"mk": "North Macedonia",
	"ml": "Mali",
	"mm": "Myanmar",
	"mn": "Mongolia",
	"mo": "Macau",
	"mp": "Northern Mariana Islands",
	"mq": "Martinique",
	"mr": "Mauritania",
	"ms": "Montserrat",
	"mt": "Malta",
	"mu": "Mauritius",
	"mv": "Maldives",
	"mw": "Malawi",
	"mx": "Mexico",
	"my": "Malaysia",
	"mz": "Mozambique",
	"na": "Namibia",
	"nc": "New Caledonia",
	"ne": "Niger",
	"nf": "Norfolk Island",
	"ng": "Nigeria",
	"ni": "Nicaragua",
	"nl": "Netherlands",
	"no": "Norway",
	"np": "Nepal",
	"nr": "Nauru",
	"nu": "Niue",
	"nz": "New Zealand",
	"om": "Oman",
	"pa": "Panama",
	"pe": "Peru",
	"pf": "French Polynesia",
	"pg": "Papua New Guinea",
	"ph": "Philippines",
	"pk": "Pakistan",
	"pl": "Poland",
	"pm": "Saint Pierre and Miquelon",
	"pn": "Pitcairn Islands",
	"pr": "Puerto Rico",
	"ps": "Palestine",
	"pt": "Portugal",
	"pw": "Palau",
	"py": "Paraguay",
	"qa": "Qatar",
	"re": "Réunion",
	"ro": "Romania",
	"rs": "Serbia",
	"ru": "Russia",
	"rw": "Rwanda",
	"sa": "Saudi Arabia",
	"sb": "Solomon Islands",
	"sc": "Seychelles",
	"sd": "Sudan",
	"se": "Sweden",
	"sg": "Singapore",
	"sh": "Saint Helena, Ascension and Tristan da Cunha",
	"si": "Slovenia",
	"sj": "Svalbard and Jan Mayen",
	"sk": "Slovakia",
	"sl": "Sierra Leone",
	"sm": "San Marino",
	"sn": "Senegal",
	"so": "Somalia",
	"sr": "Suriname",
	"ss": "South Sudan",
	"st": "São Tomé and Príncipe",
	"sv": "El Salvador",
	"sx": "Sint Maarten",
	"sy": "Syria",
	"sz": "Eswatini (Swaziland)",
	"tc": "Turks and Caicos Islands",
	"td": "Chad",
	"tf": "French Southern and Antarctic Lands",
	"tg": "Togo",
	"th": "Thailand",
	"tj": "Tajikistan",
	"tk": "Tokelau",
	"tl": "Timor-Leste",
	"tm": "Turkmenistan",
	"tn": "Tunisia",
	"to": "Tonga",
	"tr": "Turkey",
	"tt": "Trinidad and Tobago",
	"tv": "Tuvalu",
	"tw": "Taiwan",
	"tz": "Tanzania",
	"ua": "Ukraine",
	"ug": "Uganda",
	"um": "United States Minor Outlying Islands",
	"us": "United States",
	"uy": "Uruguay",
	"uz": "Uzbekistan",
	"va": "Vatican City (Holy See)",
	"vc": "Saint Vincent and the Grenadines",
	"ve": "Venezuela",
	"vg": "British Virgin Islands",
	"vi": "United States Virgin Islands",
	"vn": "Vietnam",
	"vu": "Vanuatu",
	"wf": "Wallis and Futuna",
	"ws": "Samoa",
	"xk": "Kosovo",
	"ye": "Yemen",
	"yt": "Mayotte",
	"za": "South Africa",
	"zm": "Zambia",
	"zw": "Zimbabwe"
}

export const nigeriaStates:string[]=
	[
		"Abia State",
		"Adamawa State",
		"Akwa Ibom State",
		"Anambra State",
		"Bauchi State",
		"Bayelsa State",
		"Benue State",
		"Borno State",
		"Cross River State",
		"Delta State",
		"Ebonyi State",
		"Edo State",
		"Ekiti State",
		"Enugu State",
		"Federal Capital Territory",
		"Gombe State",
		"Imo State",
		"Jigawa State",
		"Kaduna State",
		"Kano State",
		"Katsina State",
		"Kebbi State",
		"Kogi State",
		"Kwara State",
		"Lagos State",
		"Nasarawa State",
		"Niger State",
		"Ogun State",
		"Ondo State",
		"Osun State",
		"Oyo State",
		"Plateau State",
		"Rivers State",
		"Sokoto State",
		"Taraba State",
		"Yobe State",
		"Zamfara State"
		];


export const tradeMarkClasses:string[]=[
	"Chemical used in industry, science and photography, as well as in agriculture, horticulture and forestry; unprocessed artificial resting soldering preparations; manures; fire extinguishing compositions; tempering and soldering preparations; Chemical substances for preserving foodstuffs ; tanning substances; adhesive used in industry",
	"Paints vanishes, lacquers preservation against rust and against deterioration of wood; colorants; mordents; raw natural resins;  metals in foil and powder form for painters, decorators, printers and artist ",
	"Bleaching preparations and other instances for laundry use; cleaning, polishing, scouring and abrasive preparations soaps; perfumery, essential oils, cosmetics, heir lotions; dentifrices",
	"Industrial oil and greases; lubricants; dust absorption wetting and binding compositions; fuels (including motor spirit) with 31 lubricants, candles and wicks ",
	"Pharmaceutical veterinary and sanitary preparations dietetic substance s adapted for medical use, food for babies; plasters, materials for dressings; materials for stopping teeth. Dental wax; disinfectants; preparations for destroying vermin; fungicides, herbicide",
	"Common metals and their alloys;  metal building materials; transportable buildings  of metals; material of metal for railway tracks; none-electric cables and wires of common metal; ironmongery; small items of metal hardware; pipes and tubes of metal ; safes;  goods of common metal not included in other. Classes’ ores",
	"Machines and machine tools; motors and engines (except for land vehicles); machine coupling and transmission components (except for land vehicles) agricultural implements; incubators for eggs.",
	'Hand tools and implements (hand operated); cutlery; side arms; razors.',
	"Scientific, nautical, surveying, electric, photographic, cinematographic optical, weighing, measuring, signaling, checking (Supervision), life-saving and teaching apparatus and instruments; apparatus for recording transmission in reproduction of sound or images; magnetic data carriers recording disc; automatic vending machines and mechanism for coin-operated apparatus; cash registers, calculating machines, data processing equipment and computers; free-extinguishing apparatus.",
	"Surgical medical, dental and veterinary apparatus and instruments, artificial lumps, eyes and teeth; orthopedic articles; suture materials",
	"Apparatus for lighting, heating, steam generating, cooking, refrigerating, drying, ventilating, water supply and sanitary purposes.",
	"Vehicles; apparatus for locomotion by land, air or water",
	"Firearms animation and projectiles explosive fireworks",
	"Precious metals and their alloys and goods in precious metals or theological and chronometric instruments",
	"Musical instrument",
	"Paper cardboard and goods made from these materials not included in other classes printed matter; bookbinding  material; photographs ; stationery; adhesive for stationery or household purposes;  artist materials; paint brushes; typewriters  and office registers (except furniture) ; instructional and teaching materials (except apparatus); plastic printers  for packaging (not included in other classes); playing card; printers type printing blocks",
	"Rubber outta-percha,  gum, asbestos. Mica and goods made from this materials and not included in other classes; plastic in extruded form  for use in manufacture; packing, stopping and instructing materials; flexible pipes not of metal",
	"Leather and imitations of teacher,  and goods made of these materials are not included in other classes;  animals skins hides; trunks and traveling bags; umbrellas , parasols and  working sticks; whips, harness and saddler ",
	"Building materials (nonmetallic); non-metallic rigid pipes for building; asphalt, pitch and bitumen; nonmetallic transportable buildings; monuments, not of metal.",
	"furniture mirrors, picture frames; goods ( not included in other  classes) or wood , cork, reed, cane, wicker, horn, bone, ivory, whalebone shell  amber, mother-of-pearl,  meerschaum  and substitutes for all these materials  of plastics",
	"Household or kitchen utensils and containers (not of precious metal or coated therewith); cobs and sponges; brushes (except Paint brushes); brush making-materials; articles or cleaning purposes: steel wool; unworked or semi-work glass (except glass used in building glassware, porcelain and earthenware not included in other classes",
	"Ropes, string, nets tents, a wings, tarpaulin mate; sailing socks and bags ( not included in other classes0) ;  padding and stuffing materials, except of rubber or plastics); raw fibrous  textile materials",
	"Yarns and threads, for textile use",
	"Textiles and textile goods. Not included in other classes; beds and table covers",
	"Clothing footwear headgear",
	"Lace and embroider, ribbons and braid, buttons, hooks and eyes pins  and needles ; agricultural flowers",
	"Carpets, rings, mat and matting, linoleum and other material for covering existing floors;  wall hangings (non-textile)",
	"Games and playthings; gymnastic and sporting articles not included in other classes; decorations for Christmas trees",
	"Meat, fish, poultry and game; meat extracts; preserved, dried and cooked fruits and vegetables;; jellies, jams fruit sauces; eggs, milk and milk products; edible oil and fats",
	"Coffee , tea, cocoa, sugar, rice tapioca, sago, artificial coffee, flour and preparation made from cereals, bread, pastry and confectionary, ices; honey, treacle; yeast , backing-powder salt, mustard; vinegar, sauces (condiments) spice ice",
	"Agricultural, horticultural and forestry product and grains not included in other classes live animals fresh fruits and vegetables; seeds, natural plants and flowers;  foodstuffs for animals malt",
	"Beers mineral and aerated waters and other non-alcoholic drinks; fruit drinks and fruit juices; syrops and other preparations for making beverages",
	"Alcoholic beverages (except beers)",
	"Tobacco; smokers, matches ",
	"Advertising business management, Business Administration, Office functions",
	"Insurance, financial Affairs, monetary Affairs and estate affairs",
	"Building Construction, repair and, Installation services",
	"Telecommunications",
	"Transport, packaging and storage of goods, Travel arrangement ",
	"Treatments of materials",
	"Education, providing of Training, Entertainment, sporting & Cultural activities",
	"Scientific & technological services & research and design relating thereto individual analysis research services, design and development of computers, Hardware and software ",
	"Services for providing food and drinks, temporary administration ",
	"Medical services, veterinary services, hygienic & beauty care for human beings or animals, agriculture, ",
	"Legal Services, security services for the protection of property and individual, personal and social services "
];

export function MapPatentType(type:number) {
	return type===0?"Conventional":type==1?"Non-Conventional":"PCT";
}