// import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";
import adapter from "@sveltejs/adapter-static";
// import adapter from '@sveltejs/adapter-netlify';

/** @type {import('@sveltejs/kit').Config} */

const config = {
  // Consult https://kit.svelte.dev/docs/integrations#preprocessors
  // for more information about preprocessors
  preprocess: vitePreprocess(),

  kit: {
    // adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
    // If your environment is not supported, or you settled on a specific environment, switch out the adapter.
    // See https://kit.svelte.dev/docs/adapters for more information about adapters.

    adapter: adapter({
      pages: "build",
      assets: "build",
      fallback: undefined,
      precompress: false,
      strict: true,
    }),
    prerender: {
      entries: [
        "/",
        "/application",
        "/auth",
        "/dataview",
        "/files",
        "/home",
        "/home/dashboard",
        "/home/notifications",
        "/home/profile",
        "/home/search",
        "/home/support",
        "/home/finance",
        "/home/performance",
        "/home/publications",
        "/home/users",
        "/payment",
        "/payment/paid",
        "/home/payments",
        "/home/trademarkpubs",
        "/PaymentView",
        "/payment/status",
        "/publications",
        "/logout",
        "/updatesmade",
        "/metadata",
        "/statussearch",
        "/statussearch/result",
        "/availabilitysearch",
        "/home/postregistration",
        "/home/opposition",
        "/home/postregistration/search",
        "/home/postregistration/merger",
        "/home/postregistration/paid",
        "/home/postregistration/registeredusers",
        "/home/postregistration/changedata",
        "/home/postregistration/assignment",
        "/home/clerical-update",
        "/home/clerical-update/paid",
        "/home/clerical-update/search",
        "/home/clerical-update/update",
        "/home/clerical-update/patentclericalupdate",
        "/home/amendment",
        "/home/amendment/search",
        "/home/amendment/update",
        "/home/update-files",
        "/home/update-files/search",
        "/home/update-files/update",
        "/home/admin",
        "/home/admin/updatefileinfo",
        "/home/admin/fileupdatehistory",
        "/qr",
        "/patent",
        "/home/editpatentfiles",
        "/home/editattachments",
        "/home/claim-files",
        "/home/claim-files/search",
        "/home/claimrequests",
        "/home/publications/publicationstatusupdate",
        "/home/publications/publicationstatusupdate/search",
        "/home/publications/publicationstatusupdate/result",
        "/home/publications/publicationstatusupdate/statusupdateform",
        "/opposition",
        "/opposition/paid",
        "/home/file-withdrawal",
        "/home/file-withdrawal/search",
        "/home/file-withdrawal/withdrawalform",
        "/home/file-withdrawal/file-withdrawal-result",
        "/home/profile/update",
        "/home/resources",
        "/home/resources/design",
        "/home/resources/patent",
        "/home/resources/trademark",
        "/upload",
        "/home/postregistration/patentamendment",
        "/home/postregistration/patentassignment",
        "/home/postregistration/patentassignment/result",
        "/home/postregistration/patentctc",
        "/home/postregistration/patentlicense",
        "/home/postregistration/patentlicense/result",
        "/home/postregistration/patentmerger",
        "/home/postregistration/patentmerger/result",
        "/home/postregistration/patentmortgage",
        "/home/postregistration/patentmortgage/result",
        "/home/postregistration/patentamendment/result",
        "/home/postregistration/patentctc/result",
        "/statistics",
        "/statistics/financial",
        "/statistics/performance/staff",
        "/statistics/performance/units",
        "/statistics/operational",
        "/design",
        "/auth/reset-password",
        "/home/postregistration/designamendment",
        "/home/postregistration/designamendment/result",
        "/home/postregistration/designassignment",
        "/home/postregistration/designassignment/result",
        "/home/postregistration/designctc",
        "/home/postregistration/designctc/result",
        "/home/postregistration/designlicense",
        "/home/postregistration/designlicense/result",
        "/home/postregistration/designmerger",
        "/home/postregistration/designmerger/result",
        "/home/postregistration/designmortgage",
        "/home/postregistration/designmortgage/result",
        "/home/postregistration/trademarkctc",
        "/home/postregistration/trademarkctc/result",
        "/statistics/techfee",
        "/cookie-policy",
        "/counterstatement/paid",
        "/statutorydeclaration/paid",
        "/oppositionwithdrawal/paid",
        "/home/other-applications",
        "/home/iposupport",
        "/home/offline-renewal",
        "/home/offline-renewal/search",
        "/home/offline-renewal/submit"
      ],
    },
  },
};

export default config;
